blog/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^article/', include('article.urls', namespace='article'))
]

blog/main/urls.py
from django.conf.urls import url
from main import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
]

blog/article/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering= ('-pubDateTime',)
    
class Comment(models.Model):
    article = models.ForeignKey(Article)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.article.title+ '-' + str(self.id)

blog/main/models.py
from django.db import models

# Create your models here.

blog/article/forms.py
from django import forms
from article.models import Article

class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)
    
    class Meta:
        model = Article
        fields = ('title', 'content')

blog/article/views.py
from django.shortcuts import render, redirect, get_list_or_404,\
    get_object_or_404
from django.contrib import messages

from article.models import Article, Comment
from article.forms import ArticleForm
from django.db.models.query_utils import Q
# Create your views here.
def article(request):
    articles = Article.objects.all()
    itemsList = []
    for article in articles:
        items = [article]
        items.extend(list(Comment.objects.filter(article=article)))
        itemsList.append(items)
        context = {'itemsList':itemsList}
    return render(request, 'article/article.html', context)

def articleCreate(request):
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'articleForm':ArticleForm()})
    #POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已新增')
    return redirect('article:article')

def articleRead(request, articleId):
    articleToRead = get_object_or_404(Article, id=articleId)
    context = {
        'article': articleToRead,
        'comments': Comment.objects.filter(article=articleToRead)
        }
    return render(request, 'article/articleRead.html', context)

def articleUpdate(request, articleId):
    articleToUpdate = get_object_or_404(Article, id=articleId)
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=articleToUpdate)
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    # POST
    articleForm = ArticleForm(request.POST, instance=articleToUpdate)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    articleForm.save()
    messages.success(request, '文章已修改')
    return redirect('article:articleRead', articleId=articleId)

def articleDelete(request, articleId):
    if request.method == 'GET':
        return article(request)
    # POST
    articleToDelete = get_object_or_404(Article, id=articleId)
    articleToDelete.delete()
    messages.success(request, '文章已刪除')
    return redirect('article:article')

def articleSearch(request):
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter(Q(title__icontains=searchTerm) | Q(content__icontains=searchTerm))
    context = {'articles':articles, 'searchTerm0':searchTerm}
    return render(request, 'article/articleSearch.html', context)

blog/main/views.py
from django.shortcuts import render
import datetime
# Create your views here.

def main(request):
    context = {'like': 'Django 很棒', 'now': datetime.datetime.now()}
    return render(request, 'main/main.html', context)

def about(request):
    return render(request, 'main/about.html')

blog/article/templates/article/article.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<link rel="stylesheet" href="{% static '/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
{% include 'article/searchForm.html' %}
<h2>歡迎來到我的部落格</h2>
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}
<p class="inlineBlock"><a class="btn" href="{% url 'article:articleCreate' %}">新增文章</a></p>
<br><br><hr>
{% for items in itemsList %}
  {% for item in items %}
    {% if forloop.first %}
      <h3 class="inlineBlock"><a href="{% url 'article:articleRead' item.id %}">{{ item.title }}</a></h3>
      <form class="inlineBlock" method="post" action="{% url 'article:articleDelete' item.id %}">
      {% csrf_token %}
      <input class="btn" type="submit" value="刪除">
      </form>
      <p>發表時間:{{ item.pubDateTime|date:'Y-m-d H:i' }}</p>
      <div class=articleContent>{{ item.content|linebreaks|truncatechars_html:30 }}</div>
      <p>讚:{{ item.likes }}</p>
    {% else %}
      <p>
      <span class=comment>{{ item.content }}</span><br>
      <span class=commentTime>{{ item.pubDateTime|date:'m 月 d 日 H:i'}}</span>
      </p>
    {% endif %}
  {% endfor %}
<hr>
{% endfor %}

</body>
</html>

blog/article/templates/article/articleCreateUpdate.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
9-5
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<link rel="stylesheet" href="{% static '/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
{% if article %}
  <h2>修改文章</h2>
  <form method="post" action="{% url 'article:articleUpdate' article.id %}">
{% else %}
<h2>新增文章</h2>
<form method="post" action="{% url 'article:articleCreate' %}">
{% endif %}
  {% csrf_token %}
  {{ articleForm.as_p }}
  <input class="btn" type="submit" value="送出">
  <a class="btn" href="{% url 'article:article' %}">放棄</a>
</form>
</body>
</html>

blog/article/templates/article/articleRead.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<link rel="stylesheet" href="{% static '/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h3 class="inlineBlock">{{ article.title }}</h3>
<a class="btn inlineBlock" href="{% url 'article:articleUpdate' article.id %}">修改</a>
<p>發表時間:{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
<div class=articleContent>{{ article.content|linebreaks }}</div>
<p>讚:{{ article.likes }}</p>
{% for comment in comments %}
  <p>
    <span class=comment>{{ comment.content }}</span><br>
    <span class=commentTime>{{ comment.pubDateTime|date:'Y-m-d H:i'}}</span>
  </p>
{% endfor %}
</body>
</html>

blog/article/templates/article/articleSearch.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<link rel="stylesheet" href="{% static '/css/article.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>歡迎來到我的部落格</h1>
{% include 'article/searchForm.html' %}
<br><br><hr>
{% if not articles %}
  <p>查無資料</p>
{% else %}
  <table class="table table-striped table-hover">
    <tr><th>標題</th><th>發表時間</th></tr>
    {% for article in articles %}
    <tr>
      <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
      <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
</body>
</html>

blog/article/templates/article/searchForm.html
<form class="inlineBlock" action="{% url 'article:articleSearch' %}">
  <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
  <input class="btn" type="submit" value="查詢">
</form>

blog/main/templates/main/about.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>關於部落格</h2>
<p>歡迎來到我的部落格,您可盡情瀏覽並留言。</p>
</body>
</html>

blog/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<p>這是 HTML 版的 Hello world!</p>
<p>{{ like }}</p>
<p>{{ now }}</p>
</body>
</html>

blog/main/templates/main/menu.html
<ul>
<li><a href="{% url 'main:main' %}">首頁</a></li>
<li><a href="{% url 'main:about' %}">關於</a></li>
<li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>